services:
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    networks:
      mcp-network:
        aliases:
          - ollama
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:11434 || exit 0"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
  registry-service:
    build: ./registry-service
    ports:
      - "8000:8000"
    networks:
      mcp-network:
        aliases:
          - registry-service
    environment:
      - SERVICE_HOST=registry-service
      - SERVICE_PORT=8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 3

  rest-api-server:
    build: ./rest-api-server
    ports:
      - "8001:8000"
    networks:
      mcp-network:
        aliases:
          - rest-api-server
    environment:
      - SERVICE_HOST=rest-api-server
      - SERVICE_PORT=8000
      - REGISTRY_URL=http://registry-service:8000
      - USE_LOCAL_LLM=true
      - OLLAMA_API_URL=http://ollama:11434
      - OLLAMA_MODEL=phi:latest
    depends_on:
      registry-service:
        condition: service_healthy
      ollama:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/status"]
      interval: 30s
      timeout: 10s
      retries: 3

  graphql-api-server:
    build: ./graphql-api-server
    ports:
      - "8002:8000"
    networks:
      mcp-network:
        aliases:
          - graphql-api-server
    environment:
      - SERVICE_HOST=graphql-api-server
      - SERVICE_PORT=8000
      - REGISTRY_URL=http://registry-service:8000
    depends_on:
      registry-service:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/graphql"]
      interval: 30s
      timeout: 10s
      retries: 3

  mcp-server-1:
    build:
      context: .
      dockerfile: ./mcp-server-1/Dockerfile
    ports:
      - "8003:8000"
    networks:
      mcp-network:
        aliases:
          - mcp-server-1
    environment:
      - SERVICE_HOST=mcp-server-1
      - SERVICE_PORT=8000
      - REGISTRY_URL=http://registry-service:8000
      - REST_API_URL=http://rest-api-server:8000
      - OPENAI_API_KEY=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
      - LOG_TO_FILE=true
      - LOG_DIR=/app/logs
      - USE_LOCAL_LLM=true
      - OLLAMA_API_URL=http://ollama:11434
      - OLLAMA_MODEL=phi:latest
      - DEBUG=true
    volumes:
      - ./logs:/app/logs
    depends_on:
      registry-service:
        condition: service_healthy
      rest-api-server:
        condition: service_healthy
      ollama:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  mcp-server-2:
    build:
      context: .
      dockerfile: ./mcp-server-2/Dockerfile
    ports:
      - "8004:8000"
    networks:
      mcp-network:
        aliases:
          - mcp-server-2
    environment:
      - SERVICE_HOST=mcp-server-2
      - SERVICE_PORT=8000
      - REGISTRY_URL=http://registry-service:8000
      - GRAPHQL_API_URL=http://graphql-api-server:8000
      - LOG_TO_FILE=true
      - LOG_DIR=/app/logs
      - DEBUG=true
    volumes:
      - ./logs:/app/logs
    depends_on:
      registry-service:
        condition: service_healthy
      graphql-api-server:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  mcp-client:
    build: ./mcp-client
    ports:
      - "8005:8000"
    networks:
      mcp-network:
        aliases:
          - mcp-client
    environment:
      - SERVICE_HOST=mcp-client
      - SERVICE_PORT=8000
      - REGISTRY_URL=http://registry-service:8000
      - LOG_DIR=/app/logs
      - DEBUG=true
    volumes:
      - ./logs:/app/logs
    depends_on:
      registry-service:
        condition: service_healthy
      mcp-server-1:
        condition: service_healthy
      mcp-server-2:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  mcp-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16

volumes:
  ollama-data:
